# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, insights-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Code Climate Before Script
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Test with pytest
      run: |
        pip install pytest
        pytest
        
    - name: Code Climate Test Reporter
      uses: aktions/codeclimate-test-reporter@v1.1.0
      with:
        # The test reporter ID. This is a write-only ID that can only post test  reports.
        codeclimate-test-reporter-id: 7984b2de9bf4c852288f1e30d86d1b6d039f55dda5220d677364ee45d79005a6
        # The test reporter version. By default "latest" is used. If not explicitly set in semver format, caching will not work.
    
        codeclimate-test-reporter-version: latest # optional, default is latest
        # Test reporter download URL. If supplied, it will override the version  input.
    
        command: afte-build # optional, default is after-build
